### ISSUE TITLE
query string as shortcode

### ISSUE THREAD

**Issue by warengonzaga** [WarenGonzaga/shortcodes-wp#1]
It is useful to display the current query string as a shortcode in some cases.

**Comment by ChristofLee** [comment]
Hi, I would like to work on this please (I'm looking at #2 as well). I will submit a PR asap.

**Comment by warengonzaga** [comment]
Hi @ChristofLee try to submit a PR and I'll check it out.

**Comment by ChristofLee** [comment]
Please could you clarify for me. Do you mean something like `get_query_var()` or are you referring the search variable like `https://shortcodes-wp.local/?s=sample`?

It may be useful if you could provide a use case?

**Comment by warengonzaga** [comment]
> Please could you clarify for me. Do you mean something like `get_query_var()` or are you referring the search variable like `https://shortcodes-wp.local/?s=sample`?
> 
> It may be useful if you could provide a use case?

Yes, something like that... display the current parameter ``link.com/?here=value``

Another reference: https://docs.gravityview.co/article/314-the-get-merge-tag

Think of it like a shortcode version instead of a merge tag.

**Comment by ChristofLee** [comment]
Thanks that makes sense. Please see PR #6.

**Comment by warengonzaga** [comment]
> Thanks that makes sense. Please see PR #6.

added my requested changes.

**Comment by ChristofLee** [comment]
#6 has been merged so I believe this issue can be closed now.

**Comment by warengonzaga** [comment]
I agree @ChristofLee, closing this now as I merge the update to the dev branch.
