### ISSUE TITLE
wpinfo shortcode for wordpress related info

### ISSUE THREAD

**Issue by warengonzaga** [WarenGonzaga/shortcodes-wp#2]
Sample use case, I want to quickly access the time and date via shortcode.
Use something like: ``[wpinfo_current_month]`` as an example.

**Comment by ChristofLee** [comment]
Hi, I would like to work on this please. I will submit a PR asap.

**Comment by warengonzaga** [comment]
Submit your PR so I can take a look.

**Comment by ChristofLee** [comment]
Please see #5 PR. I hope this works as you hoped but please let me know if you would like any changes.

I also created a gitignore #4 to hide my VS Code settings. It was reformatting the file with PHPCBF which I didn't think you would want at this stage.

**Comment by ChristofLee** [comment]
I believe this issue can be closed now . Perhaps start a new issue for new features we would like to add?

**Comment by warengonzaga** [comment]
> I believe this issue can be closed now . Perhaps start a new issue for new features we would like to add?

For me, every time we add a feature to wp info let's create an issue for it to track it effectively.
I'm planning to automate the release of the plugin and the release of it. So I want to use the native GitHub functionalities for now.

**Comment by warengonzaga** [comment]
Mentioning #13 for the said automation task.
