### ISSUE TITLE
get the current URL w/out query parameters

### ISSUE THREAD

**Issue by warengonzaga** [WarenGonzaga/shortcodes-wp#21]
The example use case for this is when you want to get the current URL of the page and add it as part of your anchor tag.

```html
<a href="[wpinfo_current_url]?status=1">Sample</a>
```

**Expected Usage**

```html
[wpinfo_current_url with_param="false | true"]
```

For me, this is a useful feature to add as part of our shortcode WordPress information.

**Comment by warengonzaga** [comment]
I guess, good to add an option to the shortcodes whether to get the queries or not. Something like this: 
``[wpinfo_current_url query="false | true"]``

**Comment by adamsbriscoe** [comment]
i can take a stab at it

**Comment by warengonzaga** [comment]
Closing this as it is already added to this PR #27
