### ISSUE TITLE
implement WordPress coding standards

### ISSUE THREAD

**Issue by ChristofLee** [WarenGonzaga/shortcodes-wp#7]
Things like:
- Format of comments
- PHP Doc blocks

I am happy to do this change, please let me know and update this issue with 'Hacktoberfest'.

**Comment by warengonzaga** [comment]
Hi, @ChristofLee agree, we can also use the OOP approach for this so we can maintain this project easily.

**Comment by ChristofLee** [comment]
I agree.

How would you feel about using a boilerplate like "WordPress Plugin Boilerplate Generator | Ready to use WordPress Plugin Boilerplate" https://wppb.me then adding all our work so far to it.

However we decide, this would be a fairly big change. Perhaps we should have milestones, 1st to complete the in progress, 2nd look at this fairly big change.

**Comment by warengonzaga** [comment]
I'll think a little about this. I'm following the same format here: https://www.youtube.com/playlist?list=PLriKzYyLb28kR_CPMz8uierDWC2y3znI2 his coding style is neat and clean.

**Comment by ChristofLee** [comment]
Please see new PR for this issue #17 . Sorry the old PR was stale so needed to start a fresh branch.

I followed in regards to the format of comments. Everything else is now WP Standards.

**Comment by warengonzaga** [comment]
Closing this now since #17 has been merged.
