### ISSUE TITLE
namespace for shortcodes

### ISSUE THREAD

**Issue by ChristofLee** [WarenGonzaga/shortcodes-wp#8]
At the moment, if a theme or plugin has the same name as our functions then there will be an error.

I suggest re-writing what exists currently into a PHP Class and use namespaces.

I can do this for you but please let me know if you would like this. Again, please add 'Hacktoberfest'.

**Comment by warengonzaga** [comment]
I would agree, let's use ``shortcodes_wp`` for the namespace.

Then for the shortcode please use the following.
- ``[wpinfo_*]`` for info related to WP
- ``[wpuser_*]`` for info related to WP user.

**Comment by warengonzaga** [comment]
is this being followed? @ChristofLee

**Comment by ChristofLee** [comment]
Think this can be closed now as the original PR has been merged.

**Comment by warengonzaga** [comment]
Thanks for the reminder @ChristofLee! 🎉
